# EKF parameter reference:
# https://github.com/cra-ros-pkg/robot_localization/tree/humble-devel/params

ekf_local:
  ros__parameters:
    frequency: 100.0
    sensor_timeout: 0.1                   # If a sensor times out, the node will use kinematics to predict readings
    two_d_mode: true                      # We assume that the robot moves in 2d
    publish_tf: true                      # Publishes the odom -> base_link tf
    print_diagnostics: true               # See /diagnostics
    debug: false                          # Writes (LOTS of) debug info to a file

    twist0: enc_vel/raw
    twist0_config: [false, false, false,  # x, y, z
                    false, false, false,  # roll, pitch, yaw
                    true,  false, false,  # vx, vy, vz
                    false, false, false,  # vroll, vpitch, vyaw
                    false, false, false]  # accx, accy, accz
    twist0_queue_size: 10
    twist0_nodelay: true                  # Process immediately for lower latency
    twist0_differential: false            # Setting differential for twist measurements have no effect
    twist0_relative: false                # Velocity is not relative to initial sensor reading

    imu0: imu/raw
    imu0_config: [false, false, false,    # x, y, z
                  false, false, false,    # roll, pitch, yaw (yaw is false so that odom is local to start position)
                  false, false, false,    # vx, vy, vz
                  false, false, true,     # vroll, vpitch, vyaw
                  false, false, false]    # accx, accy, accz
    imu0_queue_size: 10
    imu0_nodelay: true                    # Process immediately for lower latency
    imu0_differential: false              # Setting differential for twist measurements have no effect
    imu0_relative: false                  # Velocity is not relative to initial sensor reading
