teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.535 #7.5
    scale_linear_turbo:
      x: 1.07 #15.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 20.0
    scale_angular_turbo:
      yaw: 40.0

    enable_button: 6 # L2 shoulder button
    enable_turbo_button: 4  # L1 shoulder button

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP" #keep as OPEN LOOP otherise closed loop using odom as smoothing which we don't want 
    max_velocity: [0.5, 0.0, 2.5]
    min_velocity: [-0.5, 0.0, -2.5]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"   #doesn't matter if using open loop i think
    odom_duration: 0.1
    use_realtime_priority: false
    enable_stamped_cmd_vel: false #keep at false