/**:
  ros__parameters:
    use_sim_time: true

cv_grid:
  ros__parameters:
    # Width and Height of the occupancy grid sent by CV in meters.
    Height: 200
    Width: 200
    # Resoultion of occupancy grid in square meters.
    Resolution: 0.05
    use_sim_time: true

cv_grid_transform_publisher:
  ros__parameters:
    # Width and Height of the occupancy grid sent by CV in meters.
    Height: 200
    Width: 200
    # Resoultion of occupancy grid in square meters.
    Resolution: 0.05
    use_sim_time: true
    debug: false

cv_view_transform_publisher:
  ros__parameters:
    # Width and Height of the occupancy grid sent by CV in meters.
    Height: 200
    Width: 200
    # Resoultion of occupancy grid in square meters.
    Resolution: 0.05
    use_sim_time: true
    show_debug_grid: false